from __future__ import annotations

import json
from pathlib import Path

from repo_health.models import AnalysisReport

EXPECTED_EXAMPLE_REPORTS = {
    "gogun-rgb-repo-health-inspector-report",
    "gogun-rgb-ai-hype-radar-report",
    "gogun-rgb-ai-work-rollback-logbook-report",
}


def test_real_world_example_reports_are_valid() -> None:
    report_dir = Path("examples/reports")

    for stem in EXPECTED_EXAMPLE_REPORTS:
        json_path = report_dir / f"{stem}.json"
        markdown_path = report_dir / f"{stem}.md"

        assert json_path.exists()
        assert markdown_path.exists()

        report = AnalysisReport.model_validate(json.loads(json_path.read_text(encoding="utf-8")))
        markdown = markdown_path.read_text(encoding="utf-8")

        assert 0 <= report.total_score <= 100
        assert 0 <= report.evaluated_score <= 100
        assert "Generated by repo-health-inspector" in markdown
        assert "scores can change when the repository changes" in markdown
        assert "lightweight static checks and GitHub metadata" in markdown
